### ISSUE TITLE
Why "To conform to 'HandyJSON', a class need to implement an empty initializer."?

### ISSUE THREAD

**Issue by HParis** [alibaba/HandyJSON#153]
Sample code from the document:√
```
class BasicTypes: HandyJSON {
    var int: Int = 2
    var doubleOptional: Double?
    var stringImplicitlyUnwrapped: String!

    required init() {}
}
```
Why the class must to implement an empty initializer?
What is the role of an empty initialize?

Thank you!

**Comment by xuyecan** [comment]
Before we write any value into the memory of a model instance, we have to construct an empty instance.It seams there are two ways to do this:

1. Call some low level api to malloc a segment of memory, and use some black magic to write every bit of the memory to obtain a valid instance in Swift world. It's not easy, and things always get into a mess.
2. Simply call a constructor to get an instance. But in the OO world, a class may only offer some specified constructor, and `HandyJSON` know nothing about it. That's why `HandyJSON` ask for an empty `init` function.
